### ISSUE TITLE
Wrong title in context menu

### ISSUE THREAD

**Issue by sss-user** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#2]
If I r-click a URL, the context menu shows the text contents of the clipboard rather than the URL.

For example, let's say I have previously visited a Mozilla web page. This URL is now in the clipboard. I now r-click a different URL with the intention of submitting it to one of the search engines in my drop-down list, say Virustotal. I do this by r-clicking the new URL and selecting Virustotal from the drop-down list.

URL in clipboard: https://addons.mozilla.org/en-US/firefox/addon/context-search-we/
R-clicked URL: https://github.com/CanisLupus/swift-selection-search/issues/new/choose

However, instead of ...

search: "https://github.com/CanisLupus/swift-selection-search/issues/new/choose...

... I see ...

search: "https://addons.mozilla.org/en-US/firefox/addon/context-search-we/...

If I continue, then the r-clicked URL is correctly submitted to Virustotal rather than the clipboard contents. So nothing is broken, it's just that the menu shows an incorrect text/URL selection.

If I have previously searched for some text, then this text appears in the menu rather than the desired URL, but the search still works properly.

OS is Windows 10 32-bit
Browser is Edge (Chrome)

![98630905-46703480-2370-11eb-9731-849b4626298d](https://user-images.githubusercontent.com/74175891/98721435-e8316900-23e4-11eb-96e2-a8efdc4bcc85.gif)

![98630874-35bfbe80-2370-11eb-929d-9ec6ed586d69](https://user-images.githubusercontent.com/74175891/98721442-ea93c300-23e4-11eb-9357-30266613d062.gif)

![98630854-2c365680-2370-11eb-9afa-ff232d4b2164](https://user-images.githubusercontent.com/74175891/98721444-eb2c5980-23e4-11eb-9ca7-e671dba65b05.gif)

![98630834-1aed4a00-2370-11eb-833c-c50a7a90b4ed](https://user-images.githubusercontent.com/74175891/98721446-ebc4f000-23e4-11eb-8010-c466527dd1e5.gif)

**Comment by YoshifumiFuyuno** [comment]
Hi.
Thank you for reporting.

Very unfortunately, this is a specification at this time.
Chromium (including Edge) does not support "onShown" or "OnClickData.linkText" as shown in the URL below.
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs#menus

So when you right-click on a link in Chromium, you can't get the link text in onClicked Events.

In the case of VirusTotal, it is searched by URL because it uses "{linkurl}" as the search URL.
Most other engines use "{searchTerms}".
"{searchTerms}" means a clipboard string if the selected text or link text is empty,
so The clipboard string is displayed in the context menu.


In the case of "{searchTerms}",
When I right-click on a link, I think it's possible to show the link text(not a URL) in the menu and actually pass it to the engine, is that better?

Best regards

**Comment by sss-user** [comment]
Sorry, I forgot about this issue. 

The problem is that I need to "encodeURIcomponent" for certain URLs. Using "searchTerms" would fail in such cases.

**Comment by YoshifumiFuyuno** [comment]
Hi.

Please tell me the URL where the problem occurs.
Normally, you don't need to use ```{searchTerms(encodeURIComponent)}```.

**Comment by YoshifumiFuyuno** [comment]
Hi.

Close this issue.
If you have a problem, you can always reopen it.

Best regards
