### ISSUE TITLE
Night mode hard to read

### ISSUE THREAD

**Issue by cheater** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#33]
When using "night mode" in the options page, please use dark gray background instead of black. It is easier to see. Black background is high contrast and hard to read. Instead, use the same colors as `about:addons` in Firefox.

Also please make sure checkboxes that are unchecked are not white but bright grey. As well as all the UI elements (borders, button borders, horizontal divider lines, text). You can take GitHub for an example. They use slightly more subdued colors (light gray instead of white) and it's much easier to read.

**Comment by YoshifumiFuyuno** [comment]
I checked with a new profile, and the background color of about:addons in Firefox is black (#000000).

The checkboxes will be handled as such.

**Comment by cheater** [comment]
There must be a difference somehow. On all of my profiles, it's dark gray. Maybe it has to do with Windows settings?

**Comment by YoshifumiFuyuno** [comment]
Firefox built-in color picker doesn't seem to work properly with about:addons.
It was #1c1b22, not #000000.
But it's almost black.
Confirmed with Firefox 96 and Firefox 98 (Nightly) on Ubuntu 20.04 LTS and Windows 10.
All new profiles.

![Screenshot](https://user-images.githubusercontent.com/9511854/152644232-3f68a7ed-016f-4ef6-a122-8670597003c5.png)

**Comment by cheater** [comment]
Indeed, and also notice, that the text and borders are not fully white, they're mid gray.

**Comment by YoshifumiFuyuno** [comment]
Some will be supported in the next version.
However, since different people have different color preferences, it is recommended to change the details in userContent.css.
And if possible, please share it on the Wiki. It will surely help someone and help me improve Dark Mode.

e.g. userContent.css
```CSS
@-moz-document url("moz-extension://746eb5af-b347-4c2f-8096-a804c7c1ee9b/settings/settings.html") {
  * { background-color: darkgray !important; }
}
```
Note that the url will change each time you install it.

**Comment by cheater** [comment]
Should this change be in 6.2?

Probably better to keep the issue open until this has been released.

**Comment by BubiBalboa** [comment]
I just found this fork and all seems great so far!

But the first thing I noticed is how the background in the settings page is too dark. lol

I think a lot of devs solve this by having three color schemes, light, dark grey (but not too dark!) and (OLED) black. It's a small issue but it would be nice not having to dick around with css files to change this.

**Comment by YoshifumiFuyuno** [comment]
Hi.

I don't have time to create a color scheme that suits everyone, I'm thinking of allowing users to enter their own CSS from the settings page.
Just something like "Popup/icons look -> Custom CSS".
What do you think?

The problem is that people who aren't familiar with CSS can't use it, but perhaps a simple sample could be put on the wiki.

Best regards

**Comment by BubiBalboa** [comment]
That would be a good solution, I think.

**Comment by YoshifumiFuyuno** [comment]
Hi.

Done.
I submitted version 8.1.
It can now be set from the Theme button on the hamburger menu.
Mozilla and Microsoft reviews may take up to 7 business days.

Best regards
