### ISSUE TITLE
Hash as url parameter

### ISSUE THREAD

**Issue by khabib227** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#72]
### Is your feature request related to a problem? Please describe.

First, congrats and thanks so much for this fork, is very good, much better and powerful than the original. Please add url parameters for hashs as sha256, sha1 and etc. This is essential for services like Tineye, currently I can use the context menu in one image, but I can just use the image url as search parameter, and has a issue here, because some image hosts block Tineye, and you get an error message, so in this case we can use a hash instead like it:

https://tineye.com/search/{sha1}?sort=size&order=desc&page=1 

 The extension "Multithreaded Download Manager" has a search function that allow hashs, to use with services like VirusTotal, that also need hashs, maybe you can use the code from this extension.

### Describe the solution you'd like

.

### Describe alternatives you've considered

.

**Comment by YoshifumiFuyuno** [comment]
Hi.
Thank you for your suggestion.

I think it's interesting.
However, since most services accept files from URLs as well, it is not clear how necessary it is, and some people are reluctant to have the ability to download files in extensions, so need to be careful.

For Tineye, you can use the URL below:
https://tineye.com/search?url={searchTerms}
or
https://tineye.com/search?url={linkurl}

If you absolutely need the hash, you can also calculate it using an external application and use the return value. (requires scripting knowledge)
[Launching external apps](https://github.com/YoshifumiFuyuno/Search-from-Popup-or-ContextMenu/wiki/Launching-external-apps)

Best regards

**Comment by YoshifumiFuyuno** [comment]
Sorry. I missed it.
> some image hosts block Tineye, and you get an error message

In the case of hash, the data must be an exact match to match, which is not very useful in the case of image searches, is it?
I think it would be better to add a function to upload images.
What do you think?

**Comment by khabib227** [comment]
I think that implement image upload is a thing much specific, something just to Tineye, if they change anything you need to update the plugin, don't seem interesting. The hash is generic that can be used for other services. I don't know if hashs work well for images search but all images that you upload to Tineye, they convert the url to sha1 look:

https://www.tineye.com/search?sort=size&order=desc&url=https%3A%2F%2Fwww.parentmap.com%2Fimages%2Farticle%2F7805%2FTest_sign.jpg

Open this link, now when the page load completely look at urlbar, now you have a url with sha1, seem to me that Tineye use sha1 to do the image indexation. Seem that Tineye download the image from file url and then convert the image to sha1 in the server to then search in sha1 index, like VirusTotal but for images. When a host block access to files out of his own page, in this case Tineye can't download the file, because don't has permition, and can't convert to sha1. But I made some tests and seem that if you use a url direct with sha1, Tineye don't accept, seem that need upload the image one time to activate sha1 url.

**Comment by khabib227** [comment]
Maybe the solution to a perfect image search is not hashs, look this plugin:

https://addons.mozilla.org/en-US/firefox/addon/search_by_image/

Test with this url, this host block Tineye access:

https://img.indexxx.com/images/sets/928045-x-art.jpg

Is interesting, this plugin (Search by Image) add a context menu to images, if you choose Tineye in the image above, Tineye can't search, you get a "Oops, something didn't work" message, but this plugin also has a option to open image, so use the context menu "Search by Image => Open Image". Now use context menu "Search by Image => Tineye", in this case Tineye can search, if you use this intermediate page ("Open Image" page) of the plugin this unblock the Tineye access, and the search work. :D If you can't understand may explanation please let me know. I think that it can be a great thing to your plugin, because today any plugin can "unblock" this blocked hosts, even the Tineye official plugin, except the Search by Image plugin using the "Open Image" workaround. And this can be useful not just to Tineye but also for any reverse image search services.

**Comment by YoshifumiFuyuno** [comment]
I'm sorry to have kept you waiting.

probably "Search by Image" is somehow uploading the image.
Otherwise Tineye cannot search with unknown images.
For Tineye, you can apparently search for it below.
Other image searches should be possible in similar ways.

<a href="#SPC%7B%22name%22%3A%22TinEye%20Reverse%20Image%20Search%22%2C%22searchUrl%22%3A%22javascript%3A(e%3D%3E%7Btry%7Bnew%20URL(e)%7Dcatch%7Breturn%20void%20alert(%5C%22no%20url%5C%22)%7Dfetch(e%2C%7Bmethod%3A%5C%22HEAD%5C%22%2Ccredentials%3A%5C%22omit%5C%22%2Ccache%3A%5C%22no-store%5C%22%7D).then((t%3D%3E%7Bif(!t.ok%7C%7C!(t.headers.get(%5C%22Content-Type%5C%22)%7C%7C%5C%22%5C%22).startsWith(%5C%22image%2F%5C%22)%7C%7Ce.toLowerCase().startsWith(%5C%22file%3A%5C%22))throw%20Error()%7D)).then((()%3D%3Espc.spc.openURL(%7Burl%3A%5C%22https%3A%2F%2Ftineye.com%2Fsearch%3Furl%3D%5C%22%2Be%7D))).catch((()%3D%3E%7Bconst%20t%3DArray.from(document.images).find((t%3D%3Et.src%3D%3D%3De))%3Bif(!t)return%20void%20alert(%5C%22no%20image%5C%22)%3Bconst%20n%3Ddocument.createElement(%5C%22canvas%5C%22)%3Bn.width%3Dt.naturalWidth%2Cn.height%3Dt.naturalHeight%2Cn.getContext(%5C%222d%5C%22).drawImage(t%2C0%2C0)%2Cspc.spc.openURL(%7Burl%3A%5C%22https%3A%2F%2Ftineye.com%2F%5C%22%2Cscript%3A%7Bcode%3A%60%7Bfetch(%5C%22%24%7Bn.toDataURL()%7D%5C%22).then((e%3D%3Ee.blob())).then((e%3D%3E%7Bconst%20t%3Ddocument.querySelector(%5C%22input%23upload_box%5C%22)%2Cn%3Dnew%20DataTransfer%3Bn.items.add(new%20File(%5Be%5D%2C%5C%22image%5C%22))%2Ct.files%3Dn.files%2Ct.dispatchEvent(new%20Event(%5C%22change%5C%22))%7D))%3B%7D%60%7D%7D)%7D))%7D)(%7BsearchTerms%7D)%3B%22%2C%22iconUrl%22%3A%22https%3A%2F%2Ftineye.com%2Ffavicon.ico%22%2C%22encode%22%3A%22RAW%22%2C%22contexts%22%3A%5B%22image%22%5D%7D"><img src="https://tineye.com/favicon.ico" width="16"><span class="engineName">TinEye Reverse Image Search</span></a> (It is added with one click)

* source
```javascript
javascript:(url=>{
  /* When using Chrome */
  try{
    new URL(url);
  }catch{
    alert("no url");
    return;
  }
  /* Firefox 115+. Not yet available in Chrome
  if(!URL.canParse(url)) {
    alert("no url");
    return;
  }
  */

  fetch(url, {method: "HEAD", credentials: "omit", cache: "no-store"})
    .then(response => {
      if(!(response.ok && (response.headers.get("Content-Type") || "").startsWith("image/"))
        || url.toLowerCase().startsWith("file:"))
        throw new Error();
    })
    .then(() => spc.spc.openURL({url: `https://tineye.com/search?url=${url}`}))
    .catch(() => {
      const img = Array.from(document.images).find(e => e.src === url);
      if(!img) {
        alert("no image");
        return;
      }
      const canvas = document.createElement("canvas");
      canvas.width = img.naturalWidth;
      canvas.height = img.naturalHeight;
      canvas.getContext("2d").drawImage(img, 0, 0);

      spc.spc.openURL({url: "https://tineye.com/", script: {code:`{
        fetch("${canvas.toDataURL()}")
          .then(response => response.blob())
          .then(imageBlob => {
            const input = document.querySelector("input#upload_box");
            const dt = new DataTransfer();
            dt.items.add(new File([imageBlob], "image"));
            input.files = dt.files;
            input.dispatchEvent(new Event("change"));
          });
      }`}});
    })
})({searchTerms});
```

**Comment by khabib227** [comment]
Thanks so much! Seem that this script is working well! You can add this engine as default engine, because is very useful, or at least add it on wiki examples. With this script, SPC is now the most effective reverse image search plugin for firefox.

**Comment by YoshifumiFuyuno** [comment]
Fixed to work with older Firefox.
Confirmed with Firefox ESR 102.13.0.

I'll add it to the wiki later.:thumbsup:
