### ISSUE TITLE
Respect Ctrl and Shift on popup

### ISSUE THREAD

**Issue by khabib227** [YoshifumiFuyuno/Search-from-Popup-or-ContextMenu#77]
For instance currently I have Enter as hotkey for Google, if I select some text and press Enter open a new tab following the "Hotkey search behavior" setting, if I press Tab and jump to Engine Filter Box, and press Enter, SPC search in current tab. Would be interesting allow Ctrl and Shift for both Search box and Engine Box, so if for instance I use Ctrl + Enter or + Left Click this open in new tab, if is just Enter or just Left click open in current window.

**Comment by khabib227** [comment]
Is just an idea to you think about...

**Comment by YoshifumiFuyuno** [comment]
Currently, pressing enter in the filter box works according to the "Left mouse button click" setting.
I can change the behavior with the modifier keys, but I am wondering how to assign them.

**Comment by YoshifumiFuyuno** [comment]
Hi.

Done.
I submitted version 8.1.
Filter Box. <kbd>Ctrl+Enter</kbd> now performs a right-click search, and <kbd>Shift+Enter</kbd> performs a wheel-click search.
Decorative keys such as the search box's Ctrl key were not implemented because they may be used as hotkeys.
Mozilla and Microsoft reviews may take up to 7 business days.

Best regards

**Comment by eliottmusk** [comment]
Very good, thanks so much, cheers!

**Comment by khabib227** [comment]
Very good, thanks so much, cheers!
